module.exports = {
  version: "0.2",
  language: "en",
  words: [
    // Technical terms and project-specific vocabulary
    "Insula",
    "MCP",
    "brAInwav",
    "ArcTDD",
    "OTEL",
    "WCAG",
    "OAuth",
    "JSON-RPC",
    "WebSocket",
    "SSE",
    "gRPC",
    "TypeScript",
    "ESM",
    "tsup",
    "Vitest",
    "Biome",
    "pnpm",
    "Nx",
    "Mise",
    "CLI",
    "API",
    "SDK",
    "HAR",
    "SBOM",
    "TUI",
    "UX",
    "UI",
    "README",
    "CONTRIBUTING",
    "CODESTYLE",
    "AGENTS",
    "markdownlint",
    "cspell",
    "GitHub",
    "workflow",
    "workflows",
    "actionable",
    "deterministic",
    "stateless",
    "mutex",
    "semver",
    "localhost",
    "endpoint",
    "endpoints",
    "middleware",
    "plugin",
    "plugins",
    "adapter",
    "adapters",
    "config",
    "configs",
    "linting",
    "linter",
    "formatter",
    "bundler",
    "transpiler",
    "polyfill",
    "shim",
    "async",
    "await",
    "Promise",
    "callback",
    "webhook",
    "websocket",
    "http",
    "https",
    "tcp",
    "udp",
    "dns",
    "url",
    "uri",
    "uuid",
    "jwt",
    "cors",
    "csrf",
    "xss",
    "sql",
    "nosql",
    "redis",
    "mongodb",
    "postgresql",
    "mysql",
    "sqlite",
    "dockerfile",
    "kubernetes",
    "docker",
    "containerization",
    "microservices",
    "monorepo",
    "workspace",
    "lockfile",
    "semgrep",
    "gitleaks",
    "osv"
  ],
  flagWords: [],
  ignorePaths: [
    "node_modules/**",
    ".nx/**",
    "dist/**",
    "reports/**",
    "enhanced-reports/**",
    "packages/*/node_modules/**",
    "*.log",
    "*.lock",
    "*.json",
    "*.yml",
    "*.yaml"
  ],
  overrides: [
    {
      filename: "**/*.md",
      languageSettings: [
        {
          languageId: "markdown",
          ignoreRegExpList: [
            // Ignore code blocks
            "/```[\\s\\S]*?```/g",
            // Ignore inline code
            "/`[^`]*`/g",
            // Ignore URLs
            "/https?:\\/\\/[^\\s)]+/g",
            // Ignore email addresses
            "/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}/g",
            // Ignore file paths
            "/[./][a-zA-Z0-9._/-]+\\.[a-zA-Z0-9]+/g",
            // Ignore version numbers
            "/v?\\d+\\.\\d+\\.\\d+/g",
            // Ignore hex colors
            "/#[0-9a-fA-F]{3,6}/g",
            // Ignore GitHub usernames and repos
            "/@[a-zA-Z0-9_-]+/g",
            "/[a-zA-Z0-9_-]+\\/[a-zA-Z0-9_.-]+/g"
          ]
        }
      ]
    }
  ]
};