import type { Finding } from "@brainwav/cortexdx-core";
import { extractTargetLabel } from "./targets.js";

export function buildArcTddPlan(
  stamp: Record<string, unknown>,
  findings: Finding[],
): string {
  const blockers = findings.filter((finding) => finding.severity === "blocker");
  const majors = findings.filter((finding) => finding.severity === "major");
  const minors = findings.filter((finding) => finding.severity === "minor");
  const targetLabel = extractTargetLabel(
    typeof stamp.targetLabel === "string" && stamp.targetLabel.length > 0
      ? stamp.targetLabel
      : stamp.endpoint,
  );

  const sections = [
    `# ArcTDD Implementation Plan — ${targetLabel}`,
    `**Endpoint:** ${stamp.endpoint}`,
    `**Inspected:** ${stamp.inspectedAt}`,
    `**Duration:** ${stamp.durationMs}ms`,
    "",
    "**North-Star:** Fix blockers first; majors second; address minors for production readiness.",
    "",
    "## 🚨 Critical Issues (Blockers)",
    blockers.length === 0 ? "✅ No blocking issues found!" : "",
    ...blockers.map((finding) => formatIssueWithSolution(finding, "BLOCKER")),
    "",
    "## ⚠️ Major Issues",
    majors.length === 0 ? "✅ No major issues found!" : "",
    ...majors.map((finding) => formatIssueWithSolution(finding, "MAJOR")),
    "",
    "## 📋 Minor Issues & Improvements",
    minors.length === 0 ? "✅ No minor issues found!" : "",
    ...minors
      .slice(0, 5)
      .map((finding) => formatIssueWithSolution(finding, "MINOR")),
    minors.length > 5
      ? `... and ${minors.length - 5} more minor issues (see full report)`
      : "",
    "",
    "## 🎯 Implementation Priority",
    "1. **Phase 1 (Critical):** Fix all blocker issues immediately",
    "2. **Phase 2 (Important):** Address major issues for stability",
    "3. **Phase 3 (Polish):** Resolve minor issues for production readiness",
    "",
    "## 🔧 Quick Wins",
    ...getQuickWins(findings),
    "",
    "## 📚 Resources",
    "- [MCP Protocol Specification](https://spec.modelcontextprotocol.io/)",
    "- [brAInwav MCP Best Practices](https://docs.brainwav.io/mcp/)",
    "- [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification)",
    "",
    "---",
    "*Generated by CortexDx Diagnostic System*",
  ];

  return sections.filter(Boolean).join("\n");
}

function formatIssueWithSolution(finding: Finding, severity: string): string {
  const solutions = generateSolutionSteps(finding);
  const evidence =
    finding.evidence?.map((e) => `${e.type}:${e.ref}`).join(", ") || "N/A";

  return [
    `### ${severity}: ${finding.title}`,
    `**Problem:** ${finding.description}`,
    `**Evidence:** ${evidence}`,
    `**Area:** ${finding.area}`,
    "",
    "**Solution Steps:**",
    ...solutions.map((step, i) => `${i + 1}. ${step}`),
    "",
  ].join("\n");
}

function generateSolutionSteps(finding: Finding): string[] {
  const { id, area, title, description } = finding;

  // Generate specific solutions based on finding patterns
  if (id.includes("batch.req.error") && description.includes("DOCTYPE")) {
    return [
      "**Fix routing issue:** Ensure `/mcp` endpoint returns JSON, not HTML",
      "**Check server configuration:** Verify MCP server is properly mounted at `/mcp` path",
      '**Test with:** `curl -X POST https://your-server.com/mcp -H \'Content-Type: application/json\' -d \'{"jsonrpc":"2.0","id":1,"method":"initialize"}\'`',
      "**Expected:** JSON response, not HTML error page",
    ];
  }

  if (id.includes("sse.missing") || id.includes("sse")) {
    return [
      "**Implement SSE endpoint:** Add `/events` route for Server-Sent Events",
      "**Set proper headers:** `Content-Type: text/event-stream`, `Cache-Control: no-cache`",
      "**Add keepalive:** Send periodic heartbeat messages every 15-30 seconds",
      "**Handle cleanup:** Remove clients on connection close",
      "**Test with:** `curl -N https://your-server.com/mcp/events`",
    ];
  }

  if (id.includes("disc.unknown") || id.includes("tools")) {
    return [
      "**Implement tools/list endpoint:** Add JSON-RPC method handler for `tools/list`",
      '**Return proper format:** `{"jsonrpc":"2.0","id":1,"result":{"tools":[...]}}`',
      "**Include tool schemas:** Each tool needs `name`, `description`, and `inputSchema`",
      "**Test with:** JSON-RPC call to `tools/list` method",
    ];
  }

  if (id.includes("jsonrpc.no_ping")) {
    return [
      "**Add ping method:** Implement `rpc.ping` JSON-RPC method",
      '**Return simple response:** `{"jsonrpc":"2.0","id":1,"result":"pong"}`',
      "**Optional but recommended:** Helps with connection testing and health checks",
    ];
  }

  if (id.includes("cors.preflight")) {
    return [
      "**Add CORS headers:** Include `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`",
      "**Handle OPTIONS requests:** Respond to preflight requests with proper headers",
      "**For development:** Use `Access-Control-Allow-Origin: *`",
      "**For production:** Specify exact origins for security",
    ];
  }

  if (id.includes("gov.pack.missing")) {
    return [
      "**Create .cortexdx directory:** Add governance configuration in project root",
      "**Add policy files:** Create governance policies for security gates (G0-G7)",
      "**Configure BMAD+PRP:** Set up brAInwav governance framework",
      "**Optional:** Can be skipped for basic MCP functionality",
    ];
  }

  // Generic solution for unknown issues
  return [
    `**Review ${area} implementation:** Check the ${area} related code`,
    `**Consult documentation:** Review MCP specification for ${area} requirements`,
    `**Test thoroughly:** Verify fix resolves the issue: "${title}"`,
    `**Monitor:** Ensure solution doesn't introduce new problems`,
  ];
}

function getQuickWins(findings: Finding[]): string[] {
  const quickWins = [];

  if (findings.some((f) => f.id.includes("cors"))) {
    quickWins.push(
      "• **5 min:** Add basic CORS headers to fix cross-origin requests",
    );
  }

  if (findings.some((f) => f.id.includes("jsonrpc.no_ping"))) {
    quickWins.push(
      "• **2 min:** Add simple `rpc.ping` method that returns `pong`",
    );
  }

  if (findings.some((f) => f.id.includes("batch.req.error"))) {
    quickWins.push(
      "• **10 min:** Fix routing to ensure `/mcp` returns JSON not HTML",
    );
  }

  if (findings.some((f) => f.id.includes("disc.unknown"))) {
    quickWins.push(
      "• **15 min:** Implement basic `tools/list` endpoint with empty array",
    );
  }

  if (quickWins.length === 0) {
    quickWins.push(
      "• **Great job!** No obvious quick wins - your MCP server is well implemented",
    );
  }

  return quickWins;
}
